// Browser checks of backlog blocks 1-2 on the lab appliance.
import { chromium, BASE, ADMIN, PASSWORD, WORK } from './lab.mjs';
import { randomBytes } from 'node:crypto';
const uiPassword = randomBytes(18).toString('base64url'), uiReset = randomBytes(18).toString('base64url');
import { readFileSync, mkdirSync } from 'node:fs';
const S = WORK;
const OUT = S + 'backlog-shots/'; mkdirSync(OUT, { recursive: true });
const models = JSON.parse(readFileSync(S + 'lab_models.json'));
const results = {};
const check = (item, name, ok, detail = '') => { (results[item] ||= []).push(!!ok); console.log(`[${ok ? 'OK ' : 'BAD'}] ${item.padEnd(7)} ${name.padEnd(55)} ${String(detail).slice(0, 140)}`); };
const ITALIAN = ['salvato', 'assente', 'elementi', 'Ultimo sync', ' mai', 'Durata', 'Nome', 'Disabilita', 'Precedenti', 'Successivi', 'Dettaglio', 'Ripristina', 'Confermi', 'Servizio', 'Nessun messaggio'];
const b = await chromium.launch();
const page = await b.newPage({ viewport: { width: 1440, height: 1000 }, ignoreHTTPSErrors: true });
const warnings = [];
page.on('console', m => warnings.push(m.text()));
page.on('dialog', d => d.accept());
await page.goto(`${BASE}/admin/`);
await page.waitForTimeout(1500);
check('UI-04', 'sign-in username pattern compiles and validates', await page.evaluate(() => { const i = document.querySelector('input[name=username]'); i.value = 'bad name;'; const bad = !i.checkValidity(); i.value = 'first.last+tag@example.org'; return bad && i.checkValidity(); }));
await page.fill('input[name=username]', ADMIN);
await page.fill('input[name=password]', PASSWORD);
await page.click('button.primary');
await page.waitForTimeout(3000);
const go = async (name) => { await page.getByRole('button', { name, exact: true }).first().click(); await page.waitForTimeout(2500); };
const text = async () => page.locator('body').innerText();
let italian = [];
const scan = async (where) => { const t = await page.evaluate(() => { const out = []; const w = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT); let n; while ((n = w.nextNode())) if (n.parentElement.tagName !== 'OPTION') out.push(n.textContent); return out.join('\n'); }); for (const w of ITALIAN) if (new RegExp(`\\b${w.trim()}\\b`).test(t)) italian.push(`${where}: ${w}`); };

await go('Catalogue'); await scan('Catalogue');
await page.screenshot({ path: OUT + '01-catalogue.png' });
check('UI-01', 'no failure banner for a NOT CONFIGURED repository', !(await text()).includes('synchronisation failed'), '');

await go('Repositories'); await scan('Repositories');
await page.screenshot({ path: OUT + '02-repositories.png', fullPage: true });
const cards = await page.locator('article.card').evaluateAll(els => els.map(e => ({ text: e.innerText, buttons: [...e.querySelectorAll('button')].map(x => x.innerText) })));
const disabled = cards.filter(c => c.text.includes('Disabled ·')), enabled = cards.filter(c => c.text.includes('Enabled ·'));
check('UI-07', 'disabled cards: DISABLED and only Enable', disabled.length && disabled.every(c => c.text.includes('DISABLED') && c.buttons.includes('Enable and test connection') && !c.buttons.includes('Synchronise')), disabled.length);
check('UI-07', 'enabled cards: Disable, Test, Synchronise', enabled.length && enabled.every(c => ['Disable', 'Test connection', 'Synchronise'].every(x => c.buttons.includes(x)) && !c.buttons.includes('Enable and test connection')), enabled.length);
check('UI-02', 'repository card in English', cards.some(c => /Token (saved|not set) · \d+ files found · Last synchronised/.test(c.text)), cards[0]?.text.split('\n')[2]);
await page.getByRole('button', { name: 'Add repository' }).click(); await page.waitForTimeout(800);
const form = await page.locator('.modal').innerText();
const providers = await page.locator('.modal select option').allInnerTexts();
check('UI-03', 'diffusion provider offered', providers.includes('diffusion'), providers.join(','));
await page.locator('.modal select').first().selectOption('modelscope'); await page.waitForTimeout(300);
const modelscope = await page.locator('.modal').innerText();
check('UI-03', 'help text no longer says ModelScope requires models', !modelscope.includes('ModelScope and GitHub require models') && modelscope.includes('ModelScope: newest GGUF releases'), '');
check('UI-02', 'repository form labels in English', form.includes('Name') && form.includes('HTTPS URL'), '');
await page.screenshot({ path: OUT + '03-repository-form.png' });
await page.locator('[aria-label=Close]').click(); await page.waitForTimeout(500);

await go('Users and roles'); await scan('Users');
const rows = await page.locator('article.card').evaluateAll(els => els.map(e => ({ text: e.innerText, selects: e.querySelectorAll('select').length, buttons: [...e.querySelectorAll('button')].map(x => x.innerText) })));
const mine = rows.find(r => r.text.includes(ADMIN));
check('USR-02', 'own row: no role, disable or delete controls', mine && mine.selects === 0 && !mine.buttons.includes('Delete') && mine.text.includes('Your account'), mine?.buttons);
await page.getByRole('button', { name: 'New user' }).click(); await page.waitForTimeout(600);
check('UI-04', 'new-user pattern compiles and validates', await page.evaluate(() => { const i = document.querySelector('.modal input[name=username]'); i.value = 'no spaces'; const bad = !i.checkValidity(); i.value = 'ui-test@example.org'; return bad && i.checkValidity(); }));
await page.fill('.modal input[name=username]', 'ui-test@example.org');
await page.fill('.modal input[name=password]', uiPassword);
await page.locator('.modal button.primary').click(); await page.waitForTimeout(2000);
const other = page.locator('article.card', { hasText: 'ui-test@example.org' });
await other.getByRole('button', { name: 'Reset password' }).click(); await page.waitForTimeout(600);
await page.fill('.modal input[name=password]', uiReset);
await page.locator('.modal button.primary').click(); await page.waitForTimeout(2000);
check('USR-01', 'reset from the page: must change at next sign-in', (await other.innerText()).includes('Must change the password'), await other.innerText());
await page.screenshot({ path: OUT + '04-users.png' });
await other.getByRole('button', { name: 'Delete' }).click(); await page.waitForTimeout(800); await page.locator('.modal button.primary', { hasText: 'Confirm' }).click(); await page.waitForTimeout(2000);
check('USR-02', 'delete from the page', !(await text()).includes('ui-test@example.org'), '');

await go('Runtime'); await scan('Runtime');
await page.screenshot({ path: OUT + '05-runtime.png', fullPage: true });
const rt = page.locator('article.card', { hasText: models.text_name });
const rtButtons = await rt.locator('button').allInnerTexts();
check('UI-05', 'runtime card shows the model name, not the UUID', await rt.count() && !(await rt.innerText()).includes(models.text), models.text_name);
check('UI-05', 'running model: Stop and Restart only', rtButtons.includes('Stop') && rtButtons.includes('Restart') && !rtButtons.includes('Start'), rtButtons.join(','));
await rt.getByRole('button', { name: 'View runtime log' }).click(); await page.waitForTimeout(1500);
check('UI-05', 'log title names engine and model', (await page.locator('.modal h2').innerText()).startsWith('llama.cpp log · '), await page.locator('.modal h2').innerText());
await page.locator('[aria-label=Close]').click(); await page.waitForTimeout(500);

await go('Installed models');
if (models.image) {
  const card = page.locator('article.card', { hasText: models.image_name });
  await card.getByRole('button', { name: 'Configure runtime' }).click(); await page.waitForTimeout(800);
  const labels = await page.locator('.modal .field > span').allInnerTexts();
  await page.screenshot({ path: OUT + '06-image-runtime-form.png' });
  check('UI-06', 'image model form: no text-model fields', !labels.some(l => /^(context|batch|parallel|Profile|NUMA|mlock|embeddings)$|Reasoning/.test(l)) && labels.some(l => l.startsWith('Default image model')), labels.join('|'));
  await page.locator('[aria-label=Close]').click(); await page.waitForTimeout(500);
  const tcard = page.locator('article.card', { hasText: models.text_name });
  await tcard.getByRole('button', { name: 'Configure runtime' }).click(); await page.waitForTimeout(800);
  const tlabels = await page.locator('.modal .field > span').allInnerTexts();
  check('UI-06', 'text model form keeps its fields', ['Context window', 'Profile', 'NUMA', 'Serve embeddings'].every(x => tlabels.some(l => l.startsWith(x))), tlabels.join('|'));
  await page.locator('[aria-label=Close]').click(); await page.waitForTimeout(500);
} else check('UI-06', 'image model installed', false, 'no SD 1.5 in the catalogue');

await go('Audit'); await scan('Audit');
check('UI-02', 'audit paging in English', (await text()).includes('Previous') && (await text()).includes('Next'), '');
await go('Logs'); await scan('Logs');
check('UI-02', 'logs source label in English', await page.locator('select[aria-label=Service]').count() === 1, '');

await go('System'); await scan('System · Configuration');
const tz = await page.locator('select[name=timezone]').inputValue();
check('SYS-01', 'time zone picker shows the live zone', tz === 'Europe/Rome', tz);
check('SYS-01', 'time zone is a list', (await page.locator('select[name=timezone] option').count()) > 300, await page.locator('select[name=timezone] option').count());
check('SYS-01', 'hostname shows the live one', (await page.locator('input[name=hostname]').inputValue()) === 'aios-lab', '');
await page.screenshot({ path: OUT + '07-system-configuration.png', fullPage: true });
await page.getByRole('button', { name: 'Network', exact: true }).click(); await page.waitForTimeout(1500); await scan('System · Network');
const net = await text();
check('SYS-02', 'current connection shown', net.includes('Current connection') && net.includes('10.0.2.2') && net.includes('DHCP'), '');
check('SYS-02', 'no change-ID field any more', !net.includes('Change ID'), '');
await page.screenshot({ path: OUT + '08-system-network.png', fullPage: true });
await page.getByRole('button', { name: 'Updates', exact: true }).click(); await page.waitForTimeout(1500); await scan('System · Updates');
const upd = await text();
check('SYS-03', 'OS updates status and buttons', upd.includes('Operating system updates') && upd.includes('Last check') && upd.includes('Check now') && !upd.includes('Signed JSON manifest'), '');
await page.screenshot({ path: OUT + '09-system-updates.png', fullPage: true });
await page.getByRole('button', { name: 'Backup', exact: true }).click(); await page.waitForTimeout(1000); await scan('System · Backup');
await page.getByRole('button', { name: 'Operations', exact: true }).click(); await page.waitForTimeout(1000); await scan('System · Operations');

check('UI-02', 'no Italian on any page', italian.length === 0, italian.join('; '));
check('UI-04', 'no invalid-pattern warning in the console', !warnings.some(w => w.includes('pattern')), warnings.filter(w => w.includes('pattern')).join(' '));
await b.close();
console.log('\nRESULTS');
for (const [k, v] of Object.entries(results)) console.log(`  ${k.padEnd(7)} ${v.every(Boolean) ? 'PASS' : 'FAIL'} (${v.filter(Boolean).length}/${v.length})`);
